export const countries = [
    "Albania",
    "Algeria",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bangladesh",
    "Belarus",
    "Belgium",
    "Bosnia",
    "Brazil",
    "Bulgaria",
    "Canada",
    "China",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Egypt",
    "Estonia",
    "Ethiopia",
    "France",
    "Georgia",
    "Germany",
    "Greece",
    "Herzegovina",
    "Hungary",
    "India",
    "Ireland",
    "Island",
    "Italy",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Latvia",
    "Lebanon",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Mexico",
    "Moldova",
    "Montenegro",
    "Morocco",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nigeria",
    "Norway",
    "Oman",
    "Other",
    "Pakistan",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Saudi Arabia",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Sweden",
    "Swiss",
    "Tajikistan",
    "Tennis",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "UAE",
    "UK",
    "USA",
    "Ukraine",
    "Uzbekistan",
];

export const sports = [
    "Football",
    "Basketball",
    "Tennis",
    "Golf",
    "Volleyball",
    "Baseball",
    "Rugby",
    "Running",
    "Swimming",
    "Cycling",
    "Boxing",
    "MMA",
    "Wrestling",
    "Weightlifting",
    "Powerlifting",
    "Crossfit",
    "Bodybuilding",
    "Yoga",
    "Climbing",
    "Pilates",
    "Dance",
    "Soccer",
    "Handball",
    "Water Polo",
    "Gymnastics",
    "Athletics",
    "Hockey",
    "Ice Hockey",
    "Table Tennis",
    "Badminton",
    "Other",
];

export const levels = [
    "Beginner",
    "Intermediate",
    "Advanced",
    "Professional",
];