name: Ping Supabase

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch: 

jobs:
  ping-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ping script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_URL_DB2: ${{ secrets.SUPABASE_URL_DB2 }}
          SUPABASE_ANON_KEY_DB2: ${{ secrets.SUPABASE_ANON_KEY_DB2 }}
        run: python scripts/ping_supabase.py
 
 - name: Keep Render Site Active
        env:
          RENDER_SITE_URL: ${{ secrets.RENDER_SITE_URL }}
        run: python scripts/ping_render_site.py
